# Plan One Workflow - Single Slide Planning
# Captures intent for a single slide through 5 phases
name: plan-one
description: "Plan a single slide by capturing user intent and content requirements"
author: "Slide Builder"

# Path variables
installed_path: "{project-root}/.slide-builder/workflows/plan-one"

# Workflow components
instructions: "{installed_path}/instructions.md"

# State management
theme_file: "{project-root}/.slide-builder/theme.json"
plan_file: "{project-root}/.slide-builder/single/plan.yaml"
status_file: "{project-root}/.slide-builder/status.yaml"
single_dir: "{project-root}/.slide-builder/single"

# Template matching keywords (for reference)
template_keywords:
  layout-title:
    - title
    - intro
    - opening
    - welcome
    - cover
  layout-list:
    - list
    - bullets
    - points
    - agenda
    - items
    - features
  layout-flow:
    - flow
    - process
    - timeline
    - steps
    - sequence
    - pipeline
    - workflow
  layout-columns-2:
    - compare
    - vs
    - versus
    - two
    - side-by-side
    - before
    - after
    - pros
    - cons
  layout-columns-3:
    - three
    - triad
    - options
    - pillars
    - trio
  layout-callout:
    - key
    - insight
    - callout
    - cta
    - highlight
    - quote
    - stat
    - metric
  layout-code:
    - code
    - technical
    - api
    - snippet
    - demo
    - terminal

# Variables
variables:
  workflow_version: "1.0"

template: false
standalone: true
