# Build One Workflow - Single or Deck Slide Generation
# Generates a slide from plan.yaml using a matching template or frontend-design skill
name: build-one
description: "Build the next slide (or single planned slide) from plan using theme"
author: "Slide Builder"
version: "2.0"

# Path variables
installed_path: "{project-root}/.slide-builder/workflows/build-one"

# Config paths (shareable brand assets)
config_path: "{project-root}/.slide-builder/config"
theme_file: "{config_path}/theme.json"
templates_dir: "{config_path}/templates"
samples_dir: "{config_path}/samples"

# Catalog paths (template discovery)
catalog_path: "{config_path}/catalog"
catalog_manifest: "{catalog_path}/catalog.json"

# Workflow components
instructions: "{installed_path}/instructions.md"

# State and plan files
status_file: "{project-root}/.slide-builder/status.yaml"
single_plan: "{project-root}/output/singles/plan.yaml"
# deck_plan is dynamic: output/{deck_slug}/plan.yaml (read deck_slug from status.yaml)

# Output locations - now uses project-root/output/ for clean separation
output_root: "{project-root}/output"
single_output_dir: "{output_root}/singles"
deck_output_dir: "{output_root}"  # Deck slides go to output/{slug}/slides/

# Legacy paths (for deck working files only)
deck_working_dir: "{project-root}/.slide-builder/deck"

# Template discovery is now catalog-driven
# Read catalog.json for template matching:
# 1. Match against template `id` field (exact match)
# 2. Fall back to `use_cases` array matching
# 3. Fall back to custom generation via frontend-design skill
#
# Legacy mappings below are kept for backward compatibility only
# They are used as fallback if catalog.json is missing
legacy_template_mapping:
  title: "title.html"
  agenda: "agenda.html"
  process-flow: "process-flow.html"
  comparison: "comparison.html"
  callout: "callout.html"
  technical: "technical.html"

# Slide status enum
slide_status:
  - "pending"
  - "built"
  - "failed"

# State file schema for deck slides
state_file_schema:
  slide: "number"
  edits: "[]"
  lastModified: "null"

# Variables
variables:
  workflow_version: "2.0"

template: false
standalone: true
