# Update Brand Assets Workflow - Brand Asset Catalog Management
# Manages brand assets: icons, logos, and images
name: update-brand-assets
description: "Manage brand asset catalog: classify and import icons, logos, and images"
author: "Slide Builder"

# Path variables
installed_path: "{project-root}/.slide-builder/workflows/update-brand-assets"

# Config paths
config_path: "{project-root}/.slide-builder/config"
catalog_path: "{config_path}/catalog"
brand_assets_path: "{catalog_path}/brand-assets"

# Catalog paths
icons_path: "{brand_assets_path}/icons"
icon_catalog: "{icons_path}/icon-catalog.json"
logos_path: "{brand_assets_path}/logos"
logo_catalog: "{logos_path}/logo-catalog.json"
images_path: "{brand_assets_path}/images"
images_catalog: "{images_path}/images-catalog.json"

# Workflow components
instructions: "{installed_path}/instructions.md"

# State management
state_file: "{project-root}/.slide-builder/status.yaml"

# Variables
variables:
  workflow_version: "2.0"
  icon_schema_version: "2.0"

# This workflow is standalone (manages catalog, not a document)
template: false
standalone: true
