# Add Template Workflow - User-Driven Template Creation
# Creates new templates via conversational discovery
name: add-template
description: "Create new slide templates via conversational discovery and frontend-design skill"
author: "Slide Builder"

# Path variables
installed_path: "{project-root}/.slide-builder/workflows/add-template"

# Config paths
config_path: "{project-root}/.slide-builder/config"
theme_file: "{config_path}/theme.json"
catalog_path: "{config_path}/catalog"
catalog_manifest: "{catalog_path}/catalog.json"

# Workflow components
instructions: "{installed_path}/instructions.md"

# State management
state_file: "{project-root}/.slide-builder/status.yaml"

# Variables
variables:
  workflow_version: "1.0"

# Required skills - loaded during template generation phase
required_skills:
  - skill: frontend-design
    trigger: phase-generation
    reason: "Generate HTML template based on discovered requirements"
    blocking: true

# This workflow is standalone (creates template file, not a document)
template: false
standalone: true
