name: use-template-deck
description: "Instantiate a deck template with new content, parsing constraints and replacing content"
author: "Slide Builder"

installed_path: "{project-root}/.slide-builder/workflows/use-template-deck"
instructions: "{installed_path}/instructions.md"

# Catalog paths
catalog_path: "{project-root}/.slide-builder/config/catalog"
deck_templates_manifest: "{catalog_path}/deck-templates.json"
deck_templates_folder: "{catalog_path}/deck-templates"
output_folder: "{project-root}/output"

# Theme and status files
theme_file: "{project-root}/.slide-builder/config/theme.json"
status_file: "{project-root}/.slide-builder/status.yaml"

template: false
standalone: true
